# Generated by Django 2.0.1 on 2018-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
